imports:
    - { resource: "../../config/parameters.yml" }    
    - { resource: parameters.yml }
    - { resource: "../../config/parameters.php" }	
    - { resource: "../../config/config.yml" }
    - { resource: security.yml }

services:
    rest_client:
        class:      %rest_client_class%
        arguments:  [%api_host%]

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: TB\Bundle\FrontendBundle\Entity\User 
