imports:
    - { resource: "../../config/common_parameters.yml" }    
    - { resource: parameters.yml }
    - { resource: parameters.php }	
    - { resource: "../../config/common_config.yml" }
    - { resource: security.yml }



services:
    rest_client:
        class:      %rest_client_class%
        arguments:  [%api_host%]
        