imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        collect: true
        enabled: true 

# Call API in test enviroment
twig:
    globals:
        api_host: %api_host%/app_test.php

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Use Test DB in test enviroment
doctrine:
    dbal:
        dbname:   %database_name%_test
        
liip_functional_test: ~
    
services:
    # Call API in test enviroment
    rest_client:
        class:      %rest_client_class%
        arguments:  [%api_host%/app_test.php]       
    
    # Use Test DB in test enviroment
    postgis:
        class:      TB\Bundle\APIBundle\Service\Postgis
        arguments:  [%database_host%, %database_port%, %database_name%_test, %database_user%, %database_password%]
        
# Use in memory file adapter in test enviroment
knp_gaufrette:
    adapters:
        gpx_files:
            in_memory: ~
        trail_media_files:
            in_memory: ~  
        asset_files:
            in_memory: ~               

# use different queue and exchange in test enviroment        
old_sound_rabbit_mq:
    producers:
        main:
            exchange_options: {name: %rabbit_mq_main_queue%_test, type: direct}
            queue_options:    {name: %rabbit_mq_main_queue%_test}              
