imports:
    - { resource: "../../config/parameters.yml" }    
    - { resource: parameters.yml }
    - { resource: "../../config/parameters.yml" }	
    - { resource: "../../config/config.yml" }
    - { resource: security.yml }

services:
    rest_client:
        class:      %rest_client_class%
        arguments:  [%api_host%]
        