imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

# Call API in dev enviroment
twig:
    globals:
        api_host: %api_host%/app_dev.php

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true

# Call API in dev enviroment
services:
    rest_client:
        class:      %rest_client_class%
        arguments:  [%api_host%/app_dev.php]