imports:
    - { resource: parameters.yml }
    - { resource: parameters.php }	
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        api_host: %api_host%  
    exception_controller: 'TB\Bundle\APIBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            # add and postgis types as provided by creof/doctrine2-spatial package
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType
            # add hstore type from http://github.com/easybiblabs/EasyBib_DoctrineTypes
            hstore:     EasyBib\Doctrine\Types\Hstore

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        # postgis functions as provided by creof/doctrine2-spatial package
        dql:
            numeric_functions:
                st_contains:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STContains
                st_distance:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDistance
                st_area:         CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STArea
                st_length:       CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STLength
                st_geomfromtext: CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STGeomFromText
                st_centroid:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STCentroid
                st_astext:       CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STAsText
                st_makeline:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STMakeLine	
                st_setsrid:      CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STSetSRID			

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

services:
    postgis:
        class:      %postgis_class%
        arguments:  [%database_host%, %database_port%, %database_name%, %database_user%, %database_password%]
    s3_client:
        class:      %s3_client_class% 
        factory_class:  %s3_client_class%
        factory_method: factory
        arguments:  [%aws_accesskey%, %aws_secretkey%]

        