imports:
    - { resource: "../../config/parameters.yml" }
    - { resource: parameters.yml }    
    - { resource: "../../config/parameters.php" }	
    - { resource: "../../config/config.yml" }    
    - { resource: security.yml }


# Twig Configuration 
twig:
    exception_controller: 'TB\Bundle\APIBundle\Controller\ExceptionController::showAction'

