imports:
    - { resource: "../../config/parameters.yml" }
    - { resource: parameters.yml }    
    - { resource: "../../config/parameters.php" }	
    - { resource: "../../config/config.yml" }    
    - { resource: security.yml }


# Twig Configuration 
twig:
    exception_controller: 'TB\Bundle\APIBundle\Controller\ExceptionController::showAction'

services:
    postgis:
        class:      %postgis_class%
        arguments:  [%database_host%, %database_port%, %database_name%, %database_user%, %database_password%]
    s3_client:
        class:      %s3_client_class% 
        factory_class:  %s3_client_class%
        factory_method: factory
        arguments:  [%aws_accesskey%, %aws_secretkey%]

        