imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    
# Use Test DB in test enviroment
doctrine:
    dbal:
        dbname:   %database_name%_test

# Use Test DB in test enviroment
services:
    postgis:
        class:      %postgis_class%
        arguments:  [%database_host%, %database_port%, %database_name%_test, %database_user%, %database_password%]
        
liip_functional_test: ~

# Use in memory file adapter in test enviroment
knp_gaufrette:
    adapters:
        gpx_files:
            in_memory: ~
        media_files:
            in_memory: ~